- name: Cria AP no cisco ACI
  hosts: localhost
  tasks:
  - name: Add a new AP
    cisco.aci.aci_ap:
      host: "{{ cisco_aci_endpoint }}"
      use_ssl: true
      username: "{{ cisco_aci_username }}"
      password: "{{ cisco_aci_password }}"
      tenant: "{{ tenant_name }}"
      ap: "{{ ap_name}}"
      description: "{{ ap_description }}"
      validate_certs: false
      monitoring_policy: default
      state: present
    delegate_to: localhost